source "https://rubygems.org"

gem "json"
# gem "catpix"
# gem "rmagick"
gem "rest-client"
gem "colorize"
gem "pry"
gem "activerecord"
gem "sinatra-activerecord"
gem "sqlite3"
gem "rake"
gem "require_all"
